app/models/diagnosa.py
import datetime

from flask import current_app
from flask_login import AnonymousUserMixin, UserMixin
from itsdangerous import BadSignature, SignatureExpired
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import check_password_hash, generate_password_hash

from .. import db, login_manager


class Diagnosa(db.Model):
    __tablename__ = 'datadiagnosa'
    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.Integer, db.ForeignKey('users.id'))
    tingkatkecemasan = db.Column(db.String(64))
    sedikitatautidakada = db.Column(db.Float)
    ringan = db.Column(db.Float)
    sedang = db.Column(db.Float)
    parah = db.Column(db.Float)
    datetime = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def __repr__(self):
        return '<Diagnosa {}>'.format(self.user)

app/diagnosa/forms.py
from flask import url_for
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms.fields import (BooleanField, PasswordField, SelectField,
                            StringField, SubmitField)
from wtforms.fields.html5 import EmailField
from wtforms.validators import (DataRequired, Email, EqualTo, InputRequired,
                                Length)

from app.models import Label, Pilihan, User


class DiagnosaForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired(), Length(1, 64)])
    k1 = SelectField('Merasa gelisah, cemas atau amat tegang :',
                     validators=[DataRequired()],
                     coerce=int)
    k2 = SelectField(
        'Tidak mampu menghentikan atau mengendalikan rasa khawatir :',
        validators=[DataRequired()],
        coerce=int)
    k3 = SelectField('Terlalu mengkhawatirkan berbagai hal :',
                     validators=[DataRequired()],
                     coerce=int)
    k4 = SelectField('Sulit untuk santai :',
                     validators=[DataRequired()],
                     coerce=int)
    k5 = SelectField('Sangat gelisah sehingga sulit untuk duduk diam :',
                     validators=[DataRequired()],
                     coerce=int)
    k6 = SelectField('Menjadi mudah jengkel atau lekas marah :',
                     validators=[DataRequired()],
                     coerce=int)
    k7 = SelectField(
        'Merasa takut seolah-olah sesuatu yang mengerikan/buruk mungkin terjadi :',
        validators=[DataRequired()],
        coerce=int)
    c = SelectField('Tingkat kecemasam :',
                    validators=[DataRequired()],
                    coerce=int)
    submit = SubmitField('Save')

    def __init__(self, *args, **kwargs):
        super(DiagnosaForm, self).__init__(*args, **kwargs)
        self.k1.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k2.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k3.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k4.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k5.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k6.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k7.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.c.choices = [(row.id, row.item)
                          for row in Label.query.order_by('id').all()]

app/diagnosa/__init__.py
from app.diagnosa.views import diagnosa  # noqa

app/diagnosa/views.py
import json

from flask import (Blueprint, abort, flash, jsonify, redirect, render_template,
                   request, url_for)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.decorators import admin_required, pasien_required
from app.diagnosa.bayes import (bayes, getAtribut, getC, getDataTraining,
                                getJumlahC, getJumlahData, getJumlahKriteria,
                                likehood)
from app.diagnosa.forms import DiagnosaForm
from app.email import send_email
from app.models import Diagnosa, Label, Pasien, Pilihan, Role, Training, User

diagnosa = Blueprint('diagnosa', __name__)


@diagnosa.route('/')
@login_required
@admin_required
def index():
    """Index Diagnosa page."""
    diagnosa = Pasien.query.join(User, Pasien.user == User.id).join(
        Diagnosa, Pasien.user == Diagnosa.user).add_columns(
            Pasien.id, User.first_name.label('first_name'),
            User.last_name.label('last_name'), Pasien.k1, Pasien.k2, Pasien.k3,
            Pasien.k4, Pasien.k5, Pasien.k6, Pasien.k7,
            Diagnosa.tingkatkecemasan, Diagnosa.sedikitatautidakada,
            Diagnosa.ringan, Diagnosa.sedang, Diagnosa.parah).all()
    pilihans = Pilihan.query.all()
    labels = Label.query.all()
    return render_template('diagnosa/index.html',
                           diagnosa=diagnosa,
                           pilihans=pilihans,
                           labels=labels)


@diagnosa.route('/detail/<id>', methods=['GET', 'POST'])
@login_required
@admin_required
def detail(id):
    """Detail data diagnosa."""
    trainings = Training.query.all()
    pilihans = Pilihan.query.all()
    labels = Label.query.all()
    diagnosa = Pasien.query.filter_by(id=id).join(
        User, Pasien.user == User.id).add_columns(
            Pasien.id, User.first_name.label('first_name'),
            User.last_name.label('last_name'), Pasien.k1, Pasien.k2, Pasien.k3,
            Pasien.k4, Pasien.k5, Pasien.k6, Pasien.k7, Pasien.user).first()
    k1 = getAtribut('k1')
    k2 = getAtribut('k2')
    k3 = getAtribut('k3')
    k4 = getAtribut('k4')
    k5 = getAtribut('k5')
    k6 = getAtribut('k6')
    k7 = getAtribut('k7')
    c = getC()
    lh = likehood(id)
    hasildiagnosa = Diagnosa.query.filter_by(user=diagnosa.user).add_columns(
        Diagnosa.tingkatkecemasan).first()
    return render_template('diagnosa/detail.html',
                           trainings=trainings,
                           pilihans=pilihans,
                           labels=labels,
                           diagnosa=diagnosa,
                           k1=k1,
                           k2=k2,
                           k3=k3,
                           k4=k4,
                           k5=k5,
                           k6=k6,
                           k7=k7,
                           c=c,
                           lh=lh,
                           hasildiagnosa=hasildiagnosa)


@diagnosa.route('/pasien/<id>', methods=['GET', 'POST'])
@login_required
@pasien_required
def pasien(id):
    if Pasien.query.filter_by(user=id).count() != 0:
        """data diagnosa."""
        trainings = Training.query.all()
        pilihans = Pilihan.query.all()
        labels = Label.query.all()
        diagnosa = Pasien.query.filter_by(user=id).join(
            User, Pasien.user == User.id).add_columns(
                Pasien.id, User.first_name.label('first_name'),
                User.last_name.label('last_name'), Pasien.k1, Pasien.k2,
                Pasien.k3, Pasien.k4, Pasien.k5, Pasien.k6, Pasien.k7,
                Pasien.user).first()
        k1 = getAtribut('k1')
        k2 = getAtribut('k2')
        k3 = getAtribut('k3')
        k4 = getAtribut('k4')
        k5 = getAtribut('k5')
        k6 = getAtribut('k6')
        k7 = getAtribut('k7')
        c = getC()
        lh = likehood(diagnosa.id)
        hasildiagnosa = Diagnosa.query.filter_by(user=diagnosa.user).first()
        return render_template('diagnosa/pasien.html',
                               trainings=trainings,
                               pilihans=pilihans,
                               labels=labels,
                               diagnosa=diagnosa,
                               k1=k1,
                               k2=k2,
                               k3=k3,
                               k4=k4,
                               k5=k5,
                               k6=k6,
                               k7=k7,
                               c=c,
                               lh=lh,
                               hasildiagnosa=hasildiagnosa)
    else:
        flash('Data pasien {} harus diisi'.format(current_user.full_name()),
              'warning')
        return redirect(url_for('pasien.input'))


@diagnosa.route('/pasien/detail/<id>', methods=['GET', 'POST'])
@login_required
@pasien_required
def pasien_detail(id):
    """Detail data diagnosa."""
    trainings = Training.query.all()
    pilihans = Pilihan.query.all()
    labels = Label.query.all()
    diagnosa = Pasien.query.filter_by(user=id).join(
        User, Pasien.user == User.id).add_columns(
            Pasien.id, User.first_name.label('first_name'),
            User.last_name.label('last_name'), Pasien.k1, Pasien.k2, Pasien.k3,
            Pasien.k4, Pasien.k5, Pasien.k6, Pasien.k7, Pasien.user).first()
    k1 = getAtribut('k1')
    k2 = getAtribut('k2')
    k3 = getAtribut('k3')
    k4 = getAtribut('k4')
    k5 = getAtribut('k5')
    k6 = getAtribut('k6')
    k7 = getAtribut('k7')
    c = getC()
    lh = likehood(diagnosa.id)
    hasildiagnosa = Diagnosa.query.filter_by(user=diagnosa.user).add_columns(
        Diagnosa.tingkatkecemasan).first()
    return render_template('diagnosa/pasien_detail.html',
                           trainings=trainings,
                           pilihans=pilihans,
                           labels=labels,
                           diagnosa=diagnosa,
                           k1=k1,
                           k2=k2,
                           k3=k3,
                           k4=k4,
                           k5=k5,
                           k6=k6,
                           k7=k7,
                           c=c,
                           lh=lh,
                           hasildiagnosa=hasildiagnosa)

app/pasien/__init__.py
from app.pasien.views import pasien  # noqa

app/pasien/views.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.decorators import admin_required, pasien_required
from app.diagnosa.bayes import bayes
from app.email import send_email
from app.models import Diagnosa, Label, Pasien, Pilihan, Role, User
from app.pasien.forms import PasienForm, PasienInputForm

pasien = Blueprint('pasien', __name__)


@pasien.route('/')
@login_required
@admin_required
def index():
    """Index Pasien page."""
    pasien = Pasien.query.join(User, Pasien.user == User.id).add_columns(
        Pasien.id, User.first_name.label('first_name'),
        User.last_name.label('last_name'), Pasien.k1, Pasien.k2, Pasien.k3,
        Pasien.k4, Pasien.k5, Pasien.k6, Pasien.k7).all()
    pilihans = Pilihan.query.all()
    labels = Label.query.all()
    return render_template('pasien/index.html',
                           pasien=pasien,
                           pilihans=pilihans,
                           labels=labels)


@pasien.route('/new-data', methods=['GET', 'POST'])
@login_required
@admin_required
def new_data():
    """Create a new data pasien."""
    form = PasienForm()
    if form.validate_on_submit():
        if Pasien.query.filter_by(user=form.user.data).first():
            flash('Pasien already exists.', 'form-error')
        else:
            datapasien = Pasien(user=form.user.data,
                                k1=form.k1.data,
                                k2=form.k2.data,
                                k3=form.k3.data,
                                k4=form.k4.data,
                                k5=form.k5.data,
                                k6=form.k6.data,
                                k7=form.k7.data)
            db.session.add(datapasien)
            db.session.commit()
            result = bayes(datapasien.id)
            data = Diagnosa(user=result[0],
                            tingkatkecemasan=result[1],
                            sedikitatautidakada=result[2][0][1],
                            ringan=result[2][1][1],
                            sedang=result[2][2][1],
                            parah=result[2][3][1])
            db.session.add(data)
            db.session.commit()

            name = User.query.filter_by(id=form.user.data).first()
            flash(
                'Data pasien {} successfully created & diagnosa'.format(
                    name.full_name()), 'form-success')
            # flash('Data pasien {} successfully created & diagnosa'.format(datapasien.id),
            #     'form-success')
    return render_template('pasien/new_data.html', form=form)


@pasien.route('/change/<id>', methods=['GET', 'POST'])
@login_required
@admin_required
def change(id):
    """Create a change data pasien."""
    # pasien = Pasien.query.join(User, Pasien.user == User.id).add_columns(Pasien.id,User.first_name.label('first_name'),User.last_name.label('last_name'),Pasien.k1,Pasien.k2,Pasien.k3,Pasien.k4,Pasien.k5,Pasien.k6,Pasien.k7).all()
    datapasien = Pasien.query.filter_by(id=id).first()
    form = PasienForm(obj=datapasien)
    if form.validate_on_submit():
        datapasien.user = form.user.data
        datapasien.k1 = form.k1.data,
        datapasien.k2 = form.k2.data,
        datapasien.k3 = form.k3.data,
        datapasien.k4 = form.k4.data,
        datapasien.k5 = form.k5.data,
        datapasien.k6 = form.k6.data,
        datapasien.k7 = form.k7.data
        db.session.add(datapasien)
        db.session.commit()
        result = bayes(datapasien.id)
        data = Diagnosa.query.filter_by(user=datapasien.user).first()
        data.user = result[0]
        data.tingkatkecemasan = result[1]
        data.sedikitatautidakada = result[2][0][1]
        data.ringan = result[2][1][1]
        data.sedang = result[2][2][1]
        data.parah = result[2][3][1]
        db.session.add(data)
        db.session.commit()
        name = User.query.filter_by(id=form.user.data).first()
        flash('Data pasien {} successfully changed'.format(name.full_name()),
              'form-success')
    return render_template('pasien/change_data.html', form=form)


@pasien.route('/delete/<int:data_id>')
@login_required
@admin_required
def delete(data_id):
    """Delete a data pasien."""
    data = Pasien.query.filter_by(id=data_id).first()
    user = User.query.filter_by(id=data.user).first()
    db.session.delete(data)
    db.session.commit()
    flash('Successfully deleted data %s.' % user.full_name(), 'success')
    return redirect(url_for('pasien.index'))


@pasien.route('/input', methods=['GET', 'POST'])
@login_required
@pasien_required
def input():
    """Create a new data pasien."""
    if Pasien.query.filter_by(user=current_user.id).first():
        datapasien = Pasien.query.filter_by(user=current_user.id).first()
        print(datapasien)
        form = PasienInputForm(obj=datapasien)
    else:
        form = PasienInputForm()
    if form.validate_on_submit():
        if Pasien.query.filter_by(user=current_user.id).first():
            datapasien.user = current_user.id
            datapasien.k1 = form.k1.data,
            datapasien.k2 = form.k2.data,
            datapasien.k3 = form.k3.data,
            datapasien.k4 = form.k4.data,
            datapasien.k5 = form.k5.data,
            datapasien.k6 = form.k6.data,
            datapasien.k7 = form.k7.data
            db.session.add(datapasien)
            db.session.commit()
            result = bayes(datapasien.id)
            data = Diagnosa.query.filter_by(user=datapasien.user).first()
            data.user = result[0]
            data.tingkatkecemasan = result[1]
            data.sedikitatautidakada = result[2][0][1]
            data.ringan = result[2][1][1]
            data.sedang = result[2][2][1]
            data.parah = result[2][3][1]
            db.session.add(data)
            db.session.commit()
            name = User.query.filter_by(id=current_user.id).first()
            flash(
                'Data pasien {} successfully changed'.format(name.full_name()),
                'form-success')
        else:
            datapasien = Pasien(user=current_user.id,
                                k1=form.k1.data,
                                k2=form.k2.data,
                                k3=form.k3.data,
                                k4=form.k4.data,
                                k5=form.k5.data,
                                k6=form.k6.data,
                                k7=form.k7.data)
            db.session.add(datapasien)
            db.session.commit()
            result = bayes(datapasien.id)
            data = Diagnosa(user=result[0],
                            tingkatkecemasan=result[1],
                            sedikitatautidakada=result[2][0][1],
                            ringan=result[2][1][1],
                            sedang=result[2][2][1],
                            parah=result[2][3][1])
            db.session.add(data)
            db.session.commit()

            name = User.query.filter_by(id=current_user.id).first()
            flash(
                'Data pasien {} successfully created & diagnosa'.format(
                    name.full_name()), 'form-success')
    return render_template('pasien/input.html', form=form)

app/templates/diagnosa/change_data.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('pasien.index') }}">
                <i class="caret left icon"></i>
                Back to data training
            </a>
            <h2 class="ui header">
                Change Data Training
                <div class="sub header"></div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {{ f.render_form_field(form.user) }}
                {{ f.render_form_field(form.k1) }}
                {{ f.render_form_field(form.k2) }}
                {{ f.render_form_field(form.k3) }}
                {{ f.render_form_field(form.k4) }}
                {{ f.render_form_field(form.k5) }}
                {{ f.render_form_field(form.k6) }}
                {{ f.render_form_field(form.k7) }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
            
        </div>
    </div>
{% endblock %}

app/templates/diagnosa/index.html
{% extends 'layouts/base.html' %}

{% macro pilih(pilihan_id) %}
    {% for p in pilihans %}
        {%if  pilihan_id == p.id%}
            <td>{{ p.item }}</td>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro label(label_id) %}
    {% for l in labels %}
        {%if  label_id == l.id%}
            <td>{{ l.item }}</td>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro add_menu(title, endpoint, icon=None) %}
    <a class="ui basic button" href="{{ url_for(endpoint) }}">
        {% if icon is not none %}
            <i class="{{ icon }}"></i>
        {% endif %}
        {{ title }}
    </a>
{% endmacro %}


{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve column">
            <h2 class="ui header">
                Diagnosa
            </h2>
            
            <div class="ui two column stackable grid">
                <!-- ui celled table responsive nowrap unstackable -->
                <table id="example" class="ui celled table responsive" style="width:100%">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Merasa gelisah, cemas atau amat tegang</th>
                            <th>Tidak mampu menghentikan atau mengendalikan rasa khawatir</th>
                            <th>Terlalu mengkhawatirkan berbagai hal</th>
                            <th>Sulit untuk santai</th>
                            <th>Sangat gelisah sehingga sulit untuk duduk diam</th>
                            <th>Menjadi mudah jengkel atau lekas marah</th>
                            <th>Merasa takut seolah-olah sesuatu yang mengerikan/buruk mungkin terjadi</th>
                            <th>Tingkat kecemasan</th>
                            <!-- <th>P. Sedikit/tidak ada</th>
                            <th>P. Ringan</th>
                            <th>P. Sedang</th>
                            <th>P. Parah</th> -->
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for t in diagnosa %}
                        <tr>
                            <td>{{t.first_name}} {{t.last_name}}</td>
                            {{ pilih(t.k1) }}
                            {{ pilih(t.k2) }}
                            {{ pilih(t.k3) }}
                            {{ pilih(t.k4) }}
                            {{ pilih(t.k5) }}
                            {{ pilih(t.k6) }}
                            {{ pilih(t.k7) }}
                            {% if(t.tingkatkecemasan == "Sedikit atau tidak ada") %}
                                <td bgcolor="#2185d0" style="color: white;">{{ t.tingkatkecemasan }}</td>
                            {% elif(t.tingkatkecemasan == "Ringan") %}
                                <td bgcolor="#2ecc40" style="color: white;">{{ t.tingkatkecemasan }}</td>
                            {% elif(t.tingkatkecemasan == "Sedang") %}
                                <td bgcolor="ff851b" style="color: white;">{{ t.tingkatkecemasan }}</td>
                            {% elif(t.tingkatkecemasan == "Parah") %}
                                <td bgcolor="#ff695e">{{ t.tingkatkecemasan }}</td>
                            {% endif %}
                            
                            <!-- <td>{{ t.sedikitatautidakada }}</td>
                            <td>{{ t.ringan }}</td>
                            <td>{{ t.sedang }}</td>
                            <td>{{ t.parah }}</td> -->
                            <td><a class="ui compact icon button blue" href="{{ url_for('diagnosa.detail', id=t.id) }}">Detail</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
    </script>
{% endblock %}

app/templates/diagnosa/new_data.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('pasien.index') }}">
                <i class="caret left icon"></i>
                Back to data pasien
            </a>
            <h2 class="ui header">
                Add New Data Pasien
                <div class="sub header"></div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {{ f.render_form_field(form.user) }}
                {{ f.render_form_field(form.k1) }}
                {{ f.render_form_field(form.k2) }}
                {{ f.render_form_field(form.k3) }}
                {{ f.render_form_field(form.k4) }}
                {{ f.render_form_field(form.k5) }}
                {{ f.render_form_field(form.k6) }}
                {{ f.render_form_field(form.k7) }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
            
        </div>
    </div>
{% endblock %}

app/templates/diagnosa/pasien.html
{% extends 'layouts/base.html' %}

{% macro pilih(pilihan_id) %}
    {% for p in pilihans %}
        {%if  pilihan_id == p.id%}
            <td>{{ p.item }}</td>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro label(label_id) %}
    {% for l in labels %}
        {%if  label_id == l.id%}
            <td>{{ l.item }}</td>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro add_menu(title, endpoint, icon=None) %}
    <a class="ui basic button" href="{{ url_for(endpoint) }}">
        {% if icon is not none %}
            <i class="{{ icon }}"></i>
        {% endif %}
        {{ title }}
    </a>
{% endmacro %}


{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve column">
            <h2 class="ui header">
                Hasil Diagnosa Pasien {{ diagnosa.first_name }} {{ diagnosa.last_name }}
            </h2>
            <hr>

            <div class="ui">
                <div id="piechart" style="width: 100%; height: 500px;"></div>
            </div>
            
            <div class="ui">
                <table class="ui definition table">
                    
                    <tbody>
                        <tr>
                            <td>Probabilitas Sedikit atau tidak ada</td>
                            <td>{{ hasildiagnosa.sedikitatautidakada }}</td>
                        </tr>
                        <tr>
                            <td>Probabilitas Ringan</td>
                            <td>{{hasildiagnosa.ringan}}</td>
                        </tr>
                        <tr>
                            <td>Probabilitas Sedang</td>
                            <td>{{ hasildiagnosa.sedang }}</td>
                        </tr>
                        <tr>
                            <td>Probabilitas Parah</td>
                            <td>{{ hasildiagnosa.parah }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <br>
            <div class="ui">
                {% if(hasildiagnosa.tingkatkecemasan == 'Parah') %}
                <div class="ui huge red label">
                    Berdasarkan perhitungan, maka Pasien <b>{{ diagnosa.first_name }} {{ diagnosa.last_name }}</b> mengalami tingkat gangguan kecemasan tergenerelasisikan <b>{{ hasildiagnosa.tingkatkecemasan }}</b>.
                </div>
                {% elif(hasildiagnosa.tingkatkecemasan == 'Sedang') %}
                <div class="ui huge orange label">
                    Berdasarkan perhitungan, maka Pasien <b>{{ diagnosa.first_name }} {{ diagnosa.last_name }}</b> mengalami tingkat gangguan kecemasan tergenerelasisikan <b>{{ hasildiagnosa.tingkatkecemasan }}</b>.
                </div>
                {% elif(hasildiagnosa.tingkatkecemasan == 'Ringan') %}
                <div class="ui huge green label">
                    Berdasarkan perhitungan, maka Pasien <b>{{ diagnosa.first_name }} {{ diagnosa.last_name }}</b> mengalami tingkat gangguan kecemasan tergenerelasisikan <b>{{ hasildiagnosa.tingkatkecemasan }}</b>.
                </div>
                {% elif(hasildiagnosa.tingkatkecemasan == 'Sedikit atau tidak ada') %}
                <div class="ui huge blue label">
                    Berdasarkan perhitungan, maka Pasien <b>{{ diagnosa.first_name }} {{ diagnosa.last_name }}</b> mengalami tingkat gangguan kecemasan tergenerelasisikan <b>{{ hasildiagnosa.tingkatkecemasan }}</b>.
                </div>
                {% endif %}
            </div>
            <br><br>
        </div>
    </div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Tingkat Kecemasan', '%'],
            ['Sedikit atau tidak ada', {{ hasildiagnosa.sedikitatautidakada|safe }}],
            ['Ringan', {{ hasildiagnosa.ringan|safe }}],
            ['Sedang', {{ hasildiagnosa.sedang|safe }}],
            ['Parah', {{ hasildiagnosa.parah|safe }}]
        ]);

        var options = {
            title: 'Hasil Diagnosa',
            colors: ['#3366CC', '#109618', '#EF6C00', '#DC3912']
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
    }
    </script>
{% endblock %}