app/models/pasien.py
from flask import current_app
from flask_login import AnonymousUserMixin, UserMixin
from itsdangerous import BadSignature, SignatureExpired
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import check_password_hash, generate_password_hash

from .. import db, login_manager


class Pasien(db.Model):
    __tablename__ = 'datapasien'
    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.Integer, db.ForeignKey('users.id'), unique=True)
    k1 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))
    k2 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))
    k3 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))
    k4 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))
    k5 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))
    k6 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))
    k7 = db.Column(db.Integer, db.ForeignKey('pilihan.id'))

    def __repr__(self):
        return '<Pasien {}>'.format(self.user)

app/pasien/forms.py
from flask import url_for
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms.fields import (BooleanField, PasswordField, SelectField,
                            StringField, SubmitField)
from wtforms.fields.html5 import EmailField
from wtforms.validators import (DataRequired, Email, EqualTo, InputRequired,
                                Length)

from app.models import Label, Pasien, Pilihan, Role, User


class PasienForm(FlaskForm):
    user = SelectField('Pasien :', validators=[DataRequired()], coerce=int)
    k1 = SelectField('Merasa gelisah, cemas atau amat tegang :',
                     validators=[DataRequired()],
                     coerce=int)
    k2 = SelectField(
        'Tidak mampu menghentikan atau mengendalikan rasa khawatir :',
        validators=[DataRequired()],
        coerce=int)
    k3 = SelectField('Terlalu mengkhawatirkan berbagai hal :',
                     validators=[DataRequired()],
                     coerce=int)
    k4 = SelectField('Sulit untuk santai :',
                     validators=[DataRequired()],
                     coerce=int)
    k5 = SelectField('Sangat gelisah sehingga sulit untuk duduk diam :',
                     validators=[DataRequired()],
                     coerce=int)
    k6 = SelectField('Menjadi mudah jengkel atau lekas marah :',
                     validators=[DataRequired()],
                     coerce=int)
    k7 = SelectField(
        'Merasa takut seolah-olah sesuatu yang mengerikan/buruk mungkin terjadi :',
        validators=[DataRequired()],
        coerce=int)
    submit = SubmitField('Save')

    def __init__(self, *args, **kwargs):
        super(PasienForm, self).__init__(*args, **kwargs)
        # User.query.all()
        self.user.choices = [
            (row.id, row.full_name())
            # for row in User.query.all()
            for row in User.query.filter_by(role_id=1).all()
        ]
        self.k1.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k2.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k3.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k4.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k5.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k6.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k7.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]

    def validate_pasien(self, field):
        if Pasien.query.filter_by(user=field.data).first():
            raise ValidationError('User already. (Did you mean to '
                                  '<a href="{}">Check</a>?)'.format(
                                      url_for('pasien.index')))


class PasienInputForm(FlaskForm):
    # user = StringField('Nama', validators=[InputRequired(),
    #                               Length(1, 64)])
    k1 = SelectField('Merasa gelisah, cemas atau amat tegang :',
                     validators=[DataRequired()],
                     coerce=int)
    k2 = SelectField(
        'Tidak mampu menghentikan atau mengendalikan rasa khawatir :',
        validators=[DataRequired()],
        coerce=int)
    k3 = SelectField('Terlalu mengkhawatirkan berbagai hal :',
                     validators=[DataRequired()],
                     coerce=int)
    k4 = SelectField('Sulit untuk santai :',
                     validators=[DataRequired()],
                     coerce=int)
    k5 = SelectField('Sangat gelisah sehingga sulit untuk duduk diam :',
                     validators=[DataRequired()],
                     coerce=int)
    k6 = SelectField('Menjadi mudah jengkel atau lekas marah :',
                     validators=[DataRequired()],
                     coerce=int)
    k7 = SelectField(
        'Merasa takut seolah-olah sesuatu yang mengerikan/buruk mungkin terjadi :',
        validators=[DataRequired()],
        coerce=int)
    submit = SubmitField('Save')

    def __init__(self, *args, **kwargs):
        super(PasienInputForm, self).__init__(*args, **kwargs)

        self.k1.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k2.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k3.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k4.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k5.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k6.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]
        self.k7.choices = [(row.id, row.item)
                           for row in Pilihan.query.order_by('id').all()]

    def validate_pasien(self, field):
        if Pasien.query.filter_by(user=field.data).first():
            raise ValidationError('User already. (Did you mean to '
                                  '<a href="{}">Check</a>?)'.format(
                                      url_for('pasien.index')))

app/pasien/__init__.py
from app.pasien.views import pasien  # noqa

app/pasien/views.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.decorators import admin_required, pasien_required
from app.diagnosa.bayes import bayes
from app.email import send_email
from app.models import Diagnosa, Label, Pasien, Pilihan, Role, User
from app.pasien.forms import PasienForm, PasienInputForm

pasien = Blueprint('pasien', __name__)


@pasien.route('/')
@login_required
@admin_required
def index():
    """Index Pasien page."""
    pasien = Pasien.query.join(User, Pasien.user == User.id).add_columns(
        Pasien.id, User.first_name.label('first_name'),
        User.last_name.label('last_name'), Pasien.k1, Pasien.k2, Pasien.k3,
        Pasien.k4, Pasien.k5, Pasien.k6, Pasien.k7).all()
    pilihans = Pilihan.query.all()
    labels = Label.query.all()
    return render_template('pasien/index.html',
                           pasien=pasien,
                           pilihans=pilihans,
                           labels=labels)


@pasien.route('/new-data', methods=['GET', 'POST'])
@login_required
@admin_required
def new_data():
    """Create a new data pasien."""
    form = PasienForm()
    if form.validate_on_submit():
        if Pasien.query.filter_by(user=form.user.data).first():
            flash('Pasien already exists.', 'form-error')
        else:
            datapasien = Pasien(user=form.user.data,
                                k1=form.k1.data,
                                k2=form.k2.data,
                                k3=form.k3.data,
                                k4=form.k4.data,
                                k5=form.k5.data,
                                k6=form.k6.data,
                                k7=form.k7.data)
            db.session.add(datapasien)
            db.session.commit()
            result = bayes(datapasien.id)
            data = Diagnosa(user=result[0],
                            tingkatkecemasan=result[1],
                            sedikitatautidakada=result[2][0][1],
                            ringan=result[2][1][1],
                            sedang=result[2][2][1],
                            parah=result[2][3][1])
            db.session.add(data)
            db.session.commit()

            name = User.query.filter_by(id=form.user.data).first()
            flash(
                'Data pasien {} successfully created & diagnosa'.format(
                    name.full_name()), 'form-success')
            # flash('Data pasien {} successfully created & diagnosa'.format(datapasien.id),
            #     'form-success')
    return render_template('pasien/new_data.html', form=form)


@pasien.route('/change/<id>', methods=['GET', 'POST'])
@login_required
@admin_required
def change(id):
    """Create a change data pasien."""
    # pasien = Pasien.query.join(User, Pasien.user == User.id).add_columns(Pasien.id,User.first_name.label('first_name'),User.last_name.label('last_name'),Pasien.k1,Pasien.k2,Pasien.k3,Pasien.k4,Pasien.k5,Pasien.k6,Pasien.k7).all()
    datapasien = Pasien.query.filter_by(id=id).first()
    form = PasienForm(obj=datapasien)
    if form.validate_on_submit():
        datapasien.user = form.user.data
        datapasien.k1 = form.k1.data,
        datapasien.k2 = form.k2.data,
        datapasien.k3 = form.k3.data,
        datapasien.k4 = form.k4.data,
        datapasien.k5 = form.k5.data,
        datapasien.k6 = form.k6.data,
        datapasien.k7 = form.k7.data
        db.session.add(datapasien)
        db.session.commit()
        result = bayes(datapasien.id)
        data = Diagnosa.query.filter_by(user=datapasien.user).first()
        data.user = result[0]
        data.tingkatkecemasan = result[1]
        data.sedikitatautidakada = result[2][0][1]
        data.ringan = result[2][1][1]
        data.sedang = result[2][2][1]
        data.parah = result[2][3][1]
        db.session.add(data)
        db.session.commit()
        name = User.query.filter_by(id=form.user.data).first()
        flash('Data pasien {} successfully changed'.format(name.full_name()),
              'form-success')
    return render_template('pasien/change_data.html', form=form)


@pasien.route('/delete/<int:data_id>')
@login_required
@admin_required
def delete(data_id):
    """Delete a data pasien."""
    data = Pasien.query.filter_by(id=data_id).first()
    user = User.query.filter_by(id=data.user).first()
    db.session.delete(data)
    db.session.commit()
    flash('Successfully deleted data %s.' % user.full_name(), 'success')
    return redirect(url_for('pasien.index'))


@pasien.route('/input', methods=['GET', 'POST'])
@login_required
@pasien_required
def input():
    """Create a new data pasien."""
    if Pasien.query.filter_by(user=current_user.id).first():
        datapasien = Pasien.query.filter_by(user=current_user.id).first()
        print(datapasien)
        form = PasienInputForm(obj=datapasien)
    else:
        form = PasienInputForm()
    if form.validate_on_submit():
        if Pasien.query.filter_by(user=current_user.id).first():
            datapasien.user = current_user.id
            datapasien.k1 = form.k1.data,
            datapasien.k2 = form.k2.data,
            datapasien.k3 = form.k3.data,
            datapasien.k4 = form.k4.data,
            datapasien.k5 = form.k5.data,
            datapasien.k6 = form.k6.data,
            datapasien.k7 = form.k7.data
            db.session.add(datapasien)
            db.session.commit()
            result = bayes(datapasien.id)
            data = Diagnosa.query.filter_by(user=datapasien.user).first()
            data.user = result[0]
            data.tingkatkecemasan = result[1]
            data.sedikitatautidakada = result[2][0][1]
            data.ringan = result[2][1][1]
            data.sedang = result[2][2][1]
            data.parah = result[2][3][1]
            db.session.add(data)
            db.session.commit()
            name = User.query.filter_by(id=current_user.id).first()
            flash(
                'Data pasien {} successfully changed'.format(name.full_name()),
                'form-success')
        else:
            datapasien = Pasien(user=current_user.id,
                                k1=form.k1.data,
                                k2=form.k2.data,
                                k3=form.k3.data,
                                k4=form.k4.data,
                                k5=form.k5.data,
                                k6=form.k6.data,
                                k7=form.k7.data)
            db.session.add(datapasien)
            db.session.commit()
            result = bayes(datapasien.id)
            data = Diagnosa(user=result[0],
                            tingkatkecemasan=result[1],
                            sedikitatautidakada=result[2][0][1],
                            ringan=result[2][1][1],
                            sedang=result[2][2][1],
                            parah=result[2][3][1])
            db.session.add(data)
            db.session.commit()

            name = User.query.filter_by(id=current_user.id).first()
            flash(
                'Data pasien {} successfully created & diagnosa'.format(
                    name.full_name()), 'form-success')
    return render_template('pasien/input.html', form=form)

app/templates/pasien/change_data.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve column">
            <a class="ui basic compact button" href="{{ url_for('pasien.index') }}">
                <i class="caret left icon"></i>
                Back to data training
            </a>
            <h2 class="ui header">
                Change Data Training
                <div class="sub header"></div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {{ f.render_form_field(form.user) }}
                {{ f.render_form_field(form.k1) }}
                {{ f.render_form_field(form.k2) }}
                {{ f.render_form_field(form.k3) }}
                {{ f.render_form_field(form.k4) }}
                {{ f.render_form_field(form.k5) }}
                {{ f.render_form_field(form.k6) }}
                {{ f.render_form_field(form.k7) }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
            
        </div>
    </div>
{% endblock %}

app/templates/pasien/index.html
{% extends 'layouts/base.html' %}

{% macro pilih(pilihan_id) %}
    {% for p in pilihans %}
        {%if  pilihan_id == p.id%}
            <td>{{ p.item }}</td>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro label(label_id) %}
    {% for l in labels %}
        {%if  label_id == l.id%}
            <td>{{ l.item }}</td>
        {% endif %}
    {% endfor %}
{% endmacro %}
{% macro add_menu(title, endpoint, icon=None) %}
    <a class="ui basic button" href="{{ url_for(endpoint) }}">
        {% if icon is not none %}
            <i class="{{ icon }}"></i>
        {% endif %}
        {{ title }}
    </a>
{% endmacro %}


{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve column">
            <h2 class="ui header">
                Data Pasien 
                {{ add_menu('Add', 'pasien.new_data', icon='plus icon') }}
            </h2>
            
            <div class="ui two column stackable grid">
                <table id="example" class="ui celled table" style="width:100%">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Merasa gelisah, cemas atau amat tegang</th>
                            <th>Tidak mampu menghentikan atau mengendalikan rasa khawatir</th>
                            <th>Terlalu mengkhawatirkan berbagai hal</th>
                            <th>Sulit untuk santai</th>
                            <th>Sangat gelisah sehingga sulit untuk duduk diam</th>
                            <th>Menjadi mudah jengkel atau lekas marah</th>
                            <th>Merasa takut seolah-olah sesuatu yang mengerikan/buruk mungkin terjadi</th>
                            <!-- <th>Tingkat kecemasan</th> -->
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for t in pasien %}
                        <tr>
                            <td>{{t.first_name}} {{t.last_name}}</td>
                            {{ pilih(t.k1) }}
                            {{ pilih(t.k2) }}
                            {{ pilih(t.k3) }}
                            {{ pilih(t.k4) }}
                            {{ pilih(t.k5) }}
                            {{ pilih(t.k6) }}
                            {{ pilih(t.k7) }}
                            <!-- {{ label(t.c) }} -->
                            <td><a class="ui compact icon button yellow" href="{{ url_for('pasien.change', id=t.id) }}"><i class="edit icon"></i></a> <a class="ui compact icon button red" href="{{ url_for('pasien.delete', data_id=t.id) }}"><i class="delete icon"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {{ datapasien }}
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
    </script>
{% endblock %}

app/templates/pasien/input.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve column">
            
            <h2 class="ui header">
                Form Data Pasien
                <div class="sub header">
                    Selama 2 minggu terakhir, seberapa sering Anda terganggu oleh masalah-masalah berikut? 
                </div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                
                {{ f.render_form_field(form.k1) }}
                {{ f.render_form_field(form.k2) }}
                {{ f.render_form_field(form.k3) }}
                {{ f.render_form_field(form.k4) }}
                {{ f.render_form_field(form.k5) }}
                {{ f.render_form_field(form.k6) }}
                {{ f.render_form_field(form.k7) }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
            
        </div>
    </div>
{% endblock %}

app/templates/pasien/new_data.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve column">
            <a class="ui basic compact button" href="{{ url_for('pasien.index') }}">
                <i class="caret left icon"></i>
                Back to data pasien
            </a>
            <h2 class="ui header">
                Add New Data Pasien
                <div class="sub header"></div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {{ f.render_form_field(form.user) }}
                {{ f.render_form_field(form.k1) }}
                {{ f.render_form_field(form.k2) }}
                {{ f.render_form_field(form.k3) }}
                {{ f.render_form_field(form.k4) }}
                {{ f.render_form_field(form.k5) }}
                {{ f.render_form_field(form.k6) }}
                {{ f.render_form_field(form.k7) }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
            
        </div>
    </div>
{% endblock %}